<div class="my-16 w-full pc:my-40 pc:w-auto pc:max-w-pc-size">
<div class="inline-flex px-16 pc:px-0 pc:items-center justify-center truncate pc:typography-headline-24-bold items-center typography-subtitle-18-bold pc:typography-headline-24-bold h-50 pc:h-80 bg-static-white text-text-neutral-main">
<div class="relative flex max-w-[800px] items-center line-clamp-1 pr-4 pc:typography-headline-24-bold typography-subtitle-18-bold">CityCenter 지금 떠나는 도심 호캉스!</div></div><div class="mb-16 flex pc:hidden">
<div class="swiper swiper-initialized swiper-horizontal w-full" itemtype="tab">
<div class="swiper-wrapper" style="transition-duration: 300ms; transition-delay: 0ms;">
<div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="0" style="padding-left:16px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed !font-bold pointer-events-none bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-static-white bg-static-black"><span class="invisible overflow-hidden whitespace-nowrap font-bold">서울/강북</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">서울/강북</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="1" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">서울/강남</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">서울/강남</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="2" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">경기·인천</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">경기·인천</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="3" style="padding-left:8px;padding-right:16px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">부산</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">부산</span></span></div></div></div></div></div><div class="mb-20 hidden pc:flex">
<div class="swiper swiper-initialized swiper-horizontal w-full swiper-backface-hidden" itemtype="tab">
<div class="swiper-wrapper" style="transform: translate3d(0px, 0px, 0px); transition-duration: 300ms;">
<div class="swiper-slide swiper-slide-active !w-fit max-w-full overflow-hidden last:mr-0" data-index="0" style="padding-left:0px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed !font-bold pointer-events-none bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-static-white bg-static-black"><span class="invisible overflow-hidden whitespace-nowrap font-bold">서울/강북</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">서울/강북</span></span></div></div><div class="swiper-slide swiper-slide-next !w-fit max-w-full overflow-hidden last:mr-0" data-index="1" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">서울/강남</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">서울/강남</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="2" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">경기·인천</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">경기·인천</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="3" style="padding-left:8px;padding-right:0px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">부산</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">부산</span></span></div></div></div></div></div><div class="relative w-full pc:w-pc-size">
<div class="swiper swiper-initialized swiper-horizontal swiper-backface-hidden">
<div class="swiper-wrapper" style="transform: translate3d(0px, 0px, 0px);">
<div class="swiper-slide swiper-slide-active" data-swiper-slide-index="0" style="width: 1280px; margin-right: 20px;">
<div class="items-center px-16 pc:px-0">
<div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
<div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000095518">
<div class="text-text-neutral-main pc:hidden">
<div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/22/12/640/66c72dd66abaf5.93286561.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">레스케이프 호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">154,890</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">10%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/22/12/640/66c72dd66abaf5.93286561.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">레스케이프 호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">154,890</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">10%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3001027">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/08/22/14/640/63038c0adf81e2.15608776.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">서울가든호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">104,200</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/08/22/14/640/63038c0adf81e2.15608776.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">서울가든호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">104,200</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3000607">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/25/23/640/6330e0f7bc6136.31207296.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">호텔 더 디자이너스 홍대</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">91,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">30%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/25/23/640/6330e0f7bc6136.31207296.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">호텔 더 디자이너스 홍대</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">91,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">30%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3001542">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/17/12/640/634d45d5578443.51980778.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">신라스테이 광화문</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">122,100</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">7%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/17/12/640/634d45d5578443.51980778.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">신라스테이 광화문</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">122,100</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">7%</span></div></div></div></a></div></div></div></div></div><div class="swiper-slide swiper-slide-next" data-swiper-slide-index="1" style="width: 1280px; margin-right: 20px;">
    <div class="items-center px-16 pc:px-0">
    <div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
    <div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3013410">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/28/13/640/63344c29946849.69443663.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">페어필드 바이 메리어트 서울</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">70,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">6%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/28/13/640/63344c29946849.69443663.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">페어필드 바이 메리어트 서울</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">70,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">6%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3001446">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/15/13/640/63232a0734bca7.22239062.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">인터시티 서울 호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">72,500</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">3%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/15/13/640/63232a0734bca7.22239062.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">인터시티 서울 호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">72,500</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">3%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3016266">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/08/11/11/640/62f4eaa8d434d8.16052844.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">에이든 바이 베스트웨스턴 청담</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">113,600</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/08/11/11/640/62f4eaa8d434d8.16052844.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">에이든 바이 베스트웨스턴 청담</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">113,600</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3009026">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/01/02/16/640/65943319a10e21.08232189.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">호텔 유리앤</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">75,100</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/01/02/16/640/65943319a10e21.08232189.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">호텔 유리앤</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">75,100</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="2" style="width: 1280px; margin-right: 20px;">
    <div class="items-center px-16 pc:px-0">
    <div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
    <div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000110895">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/01/14/14/640/61e1884a077a15.41091156.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">케이힐스 더테라스</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">59,900</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/01/14/14/640/61e1884a077a15.41091156.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">케이힐스 더테라스</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">59,900</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10056687">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/03/18/17/640/65f881009c8a29.80351155.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">웨이브엠호텔 웨스트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">113,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/03/18/17/640/65f881009c8a29.80351155.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">웨이브엠호텔 웨스트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">113,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000110806">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/19/18/640/63503fdba60307.82821839.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">더위크앤리조트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">112,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/19/18/640/63503fdba60307.82821839.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">더위크앤리조트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">112,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3011737">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/01/10/640/66ab65ace6c0c0.60175306.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">호텔 스카이파크 센트럴 서울 판교(구 서머셋 센트럴 분당)</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">100,800</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/01/10/640/66ab65ace6c0c0.60175306.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">호텔 스카이파크 센트럴 서울 판교(구 서머셋 센트럴 분당)</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">100,800</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="3" style="width: 1280px; margin-right: 20px;">
    <div class="items-center px-16 pc:px-0">
    <div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
    <div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3018286">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/08/04/20/640/62ec27b6052ac7.46252701.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">페어필드 바이 메리어트 부산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">72,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">2%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/08/04/20/640/62ec27b6052ac7.46252701.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">페어필드 바이 메리어트 부산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">72,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">2%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10059388">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/05/10/640/66b0a92ddc0c84.11956156.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">트레블로지 스위트 부산 센텀</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">74,200</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/05/10/640/66b0a92ddc0c84.11956156.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">트레블로지 스위트 부산 센텀</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">74,200</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000112007">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/28/11/640/63342df69579f5.05251673.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">어반스테이 서면</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">41,400</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/28/11/640/63342df69579f5.05251673.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">어반스테이 서면</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">41,400</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3020201">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/31/23/640/63605dff217cf0.76725428.png" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">라발스 호텔 부산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">112,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">44%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/31/23/640/63605dff217cf0.76725428.png" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">라발스 호텔 부산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">112,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">44%</span></div></div></div></a></div></div></div></div></div></div></div><div style="top:179px" class="absolute left-0 z-[1] hidden -translate-x-2/4 pc:block"><button aria-disabled="false" class="inline-flex items-center justify-center no-underline select-none appearance-none gap-4 typography-body-14-bold select-none aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed rounded-8 aspect-square min-h-44 pc:min-h-48 rounded-8 shadow-2 bg-static-white outline outline-1 outline-opacity-black-10 aria-disabled:bg-fill-neutral-weak3 hover-never:shadow-3 hover-never:bg-fill-neutral-weak active:shadow-3 active:bg-fill-neutral-weak focus:outline focus:outline-1 focus:outline-opacity-black-10" tabindex="0" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="size-24 pc:size-24"><path fill="currentColor" fill-rule="evenodd" d="M14.603 4.82a1.15 1.15 0 0 1 .045 1.626L9.395 12l5.253 5.554a1.15 1.15 0 0 1-1.67 1.58l-6-6.344a1.15 1.15 0 0 1 0-1.58l6-6.344a1.15 1.15 0 0 1 1.625-.045" clip-rule="evenodd"></path></svg></button></div><div style="top:179px" class="absolute right-0 top-1/2 z-[1] hidden translate-x-2/4 pc:block"><button aria-disabled="false" class="inline-flex items-center justify-center no-underline select-none appearance-none gap-4 typography-body-14-bold select-none aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed rounded-8 aspect-square min-h-44 pc:min-h-48 rounded-8 shadow-2 bg-static-white outline outline-1 outline-opacity-black-10 aria-disabled:bg-fill-neutral-weak3 hover-never:shadow-3 hover-never:bg-fill-neutral-weak active:shadow-3 active:bg-fill-neutral-weak focus:outline focus:outline-1 focus:outline-opacity-black-10" tabindex="0" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="size-24 pc:size-24"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div>