<div class="hidden pc:block"><section class="my-[4rem] flex w-full justify-center">
    <div class="pc:w-pc-size">
    <div class="relative">
    <div class="swiper swiper-initialized swiper-horizontal overflow-hidden rounded-16 border-[0.1rem] border-opacity-black-16">
    <div class="swiper-wrapper">
    <div class="swiper-slide swiper-slide-active" data-swiper-slide-index="0" style="width: 1278px;">
    <div class="flex h-[44.8rem] flex-row">
    <div><div class="relative h-[44.8rem] w-[44.8rem]">
    <div class="relative overflow-hidden aspect-[1/1] pc:aspect-[1/1] rounded-16 pc:rounded-16 h-[44.8rem] w-[44.8rem] rounded-none pc:rounded-none"><img alt="Thumbnail" class="mx-auto size-full bg-fill-neutral-weak1 object-top object-cover" src="https://yaimg.yanolja.com/v5/2025/02/04/01/67a166a21f2557.25162072.jpg"></div><div class="absolute left-0 top-0 flex h-[44.8rem] w-[44.8rem] items-center justify-center bg-opacity-black-30">
    <div class="flex h-[35.2rem] w-[35.2rem] flex-col justify-between p-8">
    <div><h2 class="text-colors-white typography-headline-32-bold-line-clamp-2">해외자유패키지 이번주 특가</h2></div><button class="inline-flex items-center justify-center align-middle no-underline select-none appearance-none rounded-8 py-4 aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed aria-disabled:border-0 aria-disabled:bg-interaction-neutral-disable-main aria-disabled:text-static-white w-fit !font-bold min-h-40 px-16 typography-body-14-regular pc:min-h-48 pc:px-16 pc:typography-subtitle-16-regular !rounded-full bg-static-white text-text-neutral-main hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1" tabindex="0" type="button"><span class="relative flex"><span class="pl-6">자세히보기</span></span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="ml-4 size-16 pc:size-18"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div></div><div class="relative m-36 mb-24 flex w-full justify-between gap-20">
    <div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10182880">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/ZFkIxp1FRFExv1ZF"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">고즈넉한 일본 소도시의 감성, 마쓰야마 자유여행</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">349,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10186712">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/Dal8YPUclg0Lm1ML"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">[후쿠오카 자유 3일] 하카타 나카스 워싱턴 호텔/시내중심/에어텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">349,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10183699">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/goeEKfOW7beHS2nq"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">[야놀자단독특가]★헤난★보라카이 반자유 여행 4/5/6일</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">599,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></a></div></div></div></div><div class="swiper-slide swiper-slide-next" data-swiper-slide-index="1" style="width: 1278px;">
    <div class="flex h-[44.8rem] flex-row">
    <div><div class="relative h-[44.8rem] w-[44.8rem]">
    <div class="relative overflow-hidden aspect-[1/1] pc:aspect-[1/1] rounded-16 pc:rounded-16 h-[44.8rem] w-[44.8rem] rounded-none pc:rounded-none"><img alt="Thumbnail" class="mx-auto size-full bg-fill-neutral-weak1 object-top object-cover" src="https://yaimg.yanolja.com/v5/2024/11/27/04/6746a1bf010891.18850833.png"></div><div class="absolute left-0 top-0 flex h-[44.8rem] w-[44.8rem] items-center justify-center bg-opacity-black-30">
    <div class="flex h-[35.2rem] w-[35.2rem] flex-col justify-between p-8">
    <div><h2 class="text-colors-white typography-headline-32-bold-line-clamp-2">5성급 호텔 코인 페이백</h2></div><button class="inline-flex items-center justify-center align-middle no-underline select-none appearance-none rounded-8 py-4 aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed aria-disabled:border-0 aria-disabled:bg-interaction-neutral-disable-main aria-disabled:text-static-white w-fit !font-bold min-h-40 px-16 typography-body-14-regular pc:min-h-48 pc:px-16 pc:typography-subtitle-16-regular !rounded-full bg-static-white text-text-neutral-main hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1" tabindex="0" type="button"><span class="relative flex"><span class="pl-6">자세히보기</span></span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="ml-4 size-16 pc:size-18"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div></div><div class="relative m-36 mb-24 flex w-full justify-between gap-20">
    <div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="/hotel/10051171">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://yaimg.yanolja.com/v5/2023/07/06/17/640/64a6fe215f4902.70455583.jpg"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">JW 메리어트 제주 리조트&amp;스파</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">1,210,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원</span></div></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="/hotel/3001233">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://yaimg.yanolja.com/v5/2024/08/30/16/640/66d1ef4a718152.28299084.jpg"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">제주 썬호텔&amp;카지노</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">116,620</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">41%</span></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="/hotel/10040392">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://yaimg.yanolja.com/v5/2022/09/20/16/640/6329e9bf0337b1.36525432.jpg"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">시그니엘 서울</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">479,160</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">60%</span></div></div></a></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="2" style="width: 1278px;">
    <div class="flex h-[44.8rem] flex-row">
    <div><div class="relative h-[44.8rem] w-[44.8rem]">
    <div class="relative overflow-hidden aspect-[1/1] pc:aspect-[1/1] rounded-16 pc:rounded-16 h-[44.8rem] w-[44.8rem] rounded-none pc:rounded-none"><img alt="Thumbnail" class="mx-auto size-full bg-fill-neutral-weak1 object-top object-cover" src="https://yaimg.yanolja.com/v5/2024/11/29/01/67491a12b33240.46082276.png"></div><div class="absolute left-0 top-0 flex h-[44.8rem] w-[44.8rem] items-center justify-center bg-opacity-black-30">
    <div class="flex h-[35.2rem] w-[35.2rem] flex-col justify-between p-8">
    <div><h2 class="text-colors-white typography-headline-32-bold-line-clamp-2">인기레저티켓 모음전</h2></div><button class="inline-flex items-center justify-center align-middle no-underline select-none appearance-none rounded-8 py-4 aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed aria-disabled:border-0 aria-disabled:bg-interaction-neutral-disable-main aria-disabled:text-static-white w-fit !font-bold min-h-40 px-16 typography-body-14-regular pc:min-h-48 pc:px-16 pc:typography-subtitle-16-regular !rounded-full bg-static-white text-text-neutral-main hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1" tabindex="0" type="button"><span class="relative flex"><span class="pl-6">자세히보기</span></span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="ml-4 size-16 pc:size-18"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div></div><div class="relative m-36 mb-24 flex w-full justify-between gap-20">
    <div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10160817">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/D1R7qUBQ0FRtNslx"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">[일산] 티니핑과 함께하는 원마운트 스노우파크(~3/3)</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">25,900</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">42%</span></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10166363">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/ukzpDo27VLG4Awc0"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">[용인] [로시즌 힐링스파]캐리비안베이 이용권 (~25/3/3)</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">20,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">48%</span></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10184637">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/b7iVTDskzjB7vSGG"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">알펜시아리조트 24/25시즌 눈썰매(2/3~3/9)</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">9,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">40%</span></div></div></a></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="3" style="width: 1278px;">
    <div class="flex h-[44.8rem] flex-row">
    <div><div class="relative h-[44.8rem] w-[44.8rem]">
    <div class="relative overflow-hidden aspect-[1/1] pc:aspect-[1/1] rounded-16 pc:rounded-16 h-[44.8rem] w-[44.8rem] rounded-none pc:rounded-none"><img alt="Thumbnail" class="mx-auto size-full bg-fill-neutral-weak1 object-top object-cover" src="https://yaimg.yanolja.com/v5/2025/01/31/05/679c5fc53c44e2.09726199.jpg"></div><div class="absolute left-0 top-0 flex h-[44.8rem] w-[44.8rem] items-center justify-center bg-opacity-black-30">
    <div class="flex h-[35.2rem] w-[35.2rem] flex-col justify-between p-8">
    <div><h2 class="text-colors-white typography-headline-32-bold-line-clamp-2">2월 인기펜션 특가</h2></div><button class="inline-flex items-center justify-center align-middle no-underline select-none appearance-none rounded-8 py-4 aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed aria-disabled:border-0 aria-disabled:bg-interaction-neutral-disable-main aria-disabled:text-static-white w-fit !font-bold min-h-40 px-16 typography-body-14-regular pc:min-h-48 pc:px-16 pc:typography-subtitle-16-regular !rounded-full bg-static-white text-text-neutral-main hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1" tabindex="0" type="button"><span class="relative flex"><span class="pl-6">자세히보기</span></span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="ml-4 size-16 pc:size-18"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div></div><div class="relative m-36 mb-24 flex w-full justify-between gap-20">
    <div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="/pension/10044604">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://yaimg.yanolja.com/v5/2024/09/06/18/640/66db446edcf222.02207883.jpg"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">경주 능남20한옥펜션</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">62,900</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">15%</span></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="/pension/10052455">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://yaimg.yanolja.com/v5/2025/02/04/08/640/67a1cb94d32f87.11479825.jpg"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">태안(안면도) 청춘캠프펜션</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">45,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원</span></div></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="/pension/10048821">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://yaimg.yanolja.com/v5/2024/11/15/11/640/673736ad29ffe7.71977820.jpg"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">가평 아이디스파펜션</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">50,100</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">15%</span></div></div></a></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="4" style="width: 1278px;">
    <div class="flex h-[44.8rem] flex-row">
    <div><div class="relative h-[44.8rem] w-[44.8rem]">
    <div class="relative overflow-hidden aspect-[1/1] pc:aspect-[1/1] rounded-16 pc:rounded-16 h-[44.8rem] w-[44.8rem] rounded-none pc:rounded-none"><img alt="Thumbnail" class="mx-auto size-full bg-fill-neutral-weak1 object-top object-cover" src="https://yaimg.yanolja.com/v5/2024/12/19/04/6763a5bcafda70.62304567.jpg"></div><div class="absolute left-0 top-0 flex h-[44.8rem] w-[44.8rem] items-center justify-center bg-opacity-black-30">
    <div class="flex h-[35.2rem] w-[35.2rem] flex-col justify-between p-8">
    <div><h2 class="text-colors-white typography-headline-32-bold-line-clamp-2">새로운 해외여행을 만나다</h2></div><button class="inline-flex items-center justify-center align-middle no-underline select-none appearance-none rounded-8 py-4 aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed aria-disabled:border-0 aria-disabled:bg-interaction-neutral-disable-main aria-disabled:text-static-white w-fit !font-bold min-h-40 px-16 typography-body-14-regular pc:min-h-48 pc:px-16 pc:typography-subtitle-16-regular !rounded-full bg-static-white text-text-neutral-main hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1" tabindex="0" type="button"><span class="relative flex"><span class="pl-6">자세히보기</span></span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="ml-4 size-16 pc:size-18"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div></div><div class="relative m-36 mb-24 flex w-full justify-between gap-20">
    <div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10184377">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/uULm0NwxBj4vHuN5"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">[F1홀릭] 교토+오사카 3일, 단1회, 스즈카 그랑프리, 세계 최고의 레이스가 펼쳐지는 꿈의 무대로 떠나요</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">2,790,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10177860">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/AuJyA48U5MZvjKmq"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">EPL스페셜, 런던5일 전일자유여행, 토트넘 1층 프리미엄좌석 관람</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">2,990,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">6%</span></div></div></a></div><div class="w-[240px]">
    <div aria-hidden="true">
    <div><div></div></div></div><a class="text-text-neutral-main" href="https://leisure-web.yanolja.com/leisure/10177922">
    <div class="overflow-hidden aspect-[3/4] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10 pc:mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" style="position:absolute;height:100%;width:100%;left:0;top:0;right:0;bottom:0;color:transparent" src="https://image6.yanolja.com/leisure/L85mIO74EhtLM7NK"></div><div class="pc:px-4">
    <div class="overflow-hidden typography-body-13-regular-line-clamp-1 pc:typography-subtitle-18-regular-line-clamp-1">EPL 런던 프리미엄, 런던 8일, 토트넘경기 프리미엄좌석 관람</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[1.6rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-body-13-bold pc:typography-subtitle-20-bold">4,690,000</span><span class="typography-caption-11-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-body-13-regular text-text-primary-main pc:typography-subtitle-20-regular">9%</span></div></div></a></div></div></div></div></div></div><div class="absolute left-0 z-[1] hidden -translate-x-2/4 pc:block top-1/2 -translate-y-2/4"><button aria-disabled="false" class="inline-flex items-center justify-center no-underline select-none appearance-none gap-4 typography-body-14-bold select-none aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed rounded-8 aspect-square min-h-44 pc:min-h-48 rounded-8 shadow-2 bg-static-white outline outline-1 outline-opacity-black-10 aria-disabled:bg-fill-neutral-weak3 hover-never:shadow-3 hover-never:bg-fill-neutral-weak active:shadow-3 active:bg-fill-neutral-weak focus:outline focus:outline-1 focus:outline-opacity-black-10" tabindex="0" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="size-24 pc:size-24"><path fill="currentColor" fill-rule="evenodd" d="M14.603 4.82a1.15 1.15 0 0 1 .045 1.626L9.395 12l5.253 5.554a1.15 1.15 0 0 1-1.67 1.58l-6-6.344a1.15 1.15 0 0 1 0-1.58l6-6.344a1.15 1.15 0 0 1 1.625-.045" clip-rule="evenodd"></path></svg></button></div><div class="absolute right-0 z-[1] hidden translate-x-2/4 pc:block top-1/2 -translate-y-2/4"><button aria-disabled="false" class="inline-flex items-center justify-center no-underline select-none appearance-none gap-4 typography-body-14-bold select-none aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed rounded-8 aspect-square min-h-44 pc:min-h-48 rounded-8 shadow-2 bg-static-white outline outline-1 outline-opacity-black-10 aria-disabled:bg-fill-neutral-weak3 hover-never:shadow-3 hover-never:bg-fill-neutral-weak active:shadow-3 active:bg-fill-neutral-weak focus:outline focus:outline-1 focus:outline-opacity-black-10" tabindex="0" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="size-24 pc:size-24"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div></section></div>