<div class="my-16 w-full pc:my-40 pc:w-auto pc:max-w-pc-size">
<div class="inline-flex px-16 pc:px-0 pc:items-center justify-center truncate pc:typography-headline-24-bold items-center typography-subtitle-18-bold pc:typography-headline-24-bold h-50 pc:h-80 bg-static-white text-text-neutral-main">
<div class="relative flex max-w-[800px] items-center line-clamp-1 pr-4 pc:typography-headline-24-bold typography-subtitle-18-bold">Vacation 호캉스 가기 좋은 날씨</div></div><div class="mb-16 flex pc:hidden">
<div class="swiper swiper-initialized swiper-horizontal w-full" itemtype="tab">
<div class="swiper-wrapper" style="transition-duration: 300ms; transition-delay: 0ms;">
<div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="0" style="padding-left:16px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed !font-bold pointer-events-none bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-static-white bg-static-black"><span class="invisible overflow-hidden whitespace-nowrap font-bold">강원</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">강원</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="1" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">제주</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">제주</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="2" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">경상</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">경상</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="3" style="padding-left:8px;padding-right:16px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">충청전라</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">충청전라</span></span></div></div></div></div></div><div class="mb-20 hidden pc:flex">
<div class="swiper swiper-initialized swiper-horizontal w-full swiper-backface-hidden" itemtype="tab">
<div class="swiper-wrapper" style="transform: translate3d(0px, 0px, 0px); transition-duration: 300ms;">
<div class="swiper-slide swiper-slide-active !w-fit max-w-full overflow-hidden last:mr-0" data-index="0" style="padding-left:0px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed !font-bold pointer-events-none bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-static-white bg-static-black"><span class="invisible overflow-hidden whitespace-nowrap font-bold">강원</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">강원</span></span></div></div><div class="swiper-slide swiper-slide-next !w-fit max-w-full overflow-hidden last:mr-0" data-index="1" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">제주</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">제주</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="2" style="padding-left:8px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">경상</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">경상</span></span></div></div><div class="swiper-slide !w-fit max-w-full overflow-hidden last:mr-0" data-index="3" style="padding-left:8px;padding-right:0px" tabindex="0">
<div class="relative flex items-center justify-center min-h-36 pc:min-h-42 py-4 px-16 pc:px-20 rounded-capsule typography-body-13-regular pc:typography-subtitle-16-regular  cursor-pointer select-none disabled:pointer-events-none disabled:cursor-not-allowed hover-never:bg-interaction-neutral-presshover-weak1 active:bg-interaction-neutral-presshover-weak1 bg-fill-neutral-weak disabled:bg-fill-neutral-weak disabled:text-interaction-neutral-disable-main text-text-neutral-sub"><span class="invisible overflow-hidden whitespace-nowrap font-bold">충청전라</span><span class="absolute inset-0 flex items-center justify-center overflow-hidden whitespace-nowrap"><span class="relative">충청전라</span></span></div></div></div></div></div><div class="relative w-full pc:w-pc-size">
<div class="swiper swiper-initialized swiper-horizontal swiper-backface-hidden">
<div class="swiper-wrapper" style="transform: translate3d(0px, 0px, 0px);">
<div class="swiper-slide swiper-slide-active" data-swiper-slide-index="0" style="width: 1280px; margin-right: 20px;">
<div class="items-center px-16 pc:px-0">
<div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
<div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3013417">
<div class="text-text-neutral-main pc:hidden">
<div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/17/15/640/634d7563600ed4.17945107.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">강릉 세인트존스호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">88,600</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/17/15/640/634d7563600ed4.17945107.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">강릉 세인트존스호텔</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">88,600</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10042068">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/03/28/18/640/64232b9a66f178.61586225.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">체스터톤스 속초</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">50,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/03/28/18/640/64232b9a66f178.61586225.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">체스터톤스 속초</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">50,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10043064">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/10/22/10/640/67177d84d878a1.74229627.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">어반스테이 속초등대해변</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">39,500</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/10/22/10/640/67177d84d878a1.74229627.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">어반스테이 속초등대해변</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">39,500</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10056121">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/10/11/17/640/67095c8b79d6c8.09447040.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">체스터톤스 낙산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">39,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/10/11/17/640/67095c8b79d6c8.09447040.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">체스터톤스 낙산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">39,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div></div></div></div><div class="swiper-slide swiper-slide-next" data-swiper-slide-index="1" style="width: 1280px; margin-right: 20px;">
    <div class="items-center px-16 pc:px-0">
    <div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
    <div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3000768">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/10/17/11/640/652e6e83820500.84583731.PNG" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">더 그랜드 섬오름</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">115,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/10/17/11/640/652e6e83820500.84583731.PNG" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">더 그랜드 섬오름</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">115,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10042158">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/01/30/11/640/63d7ac421dc7f9.32093210.png" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">호텔 브릿지 서귀포</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">56,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/01/30/11/640/63d7ac421dc7f9.32093210.png" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">호텔 브릿지 서귀포</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">56,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3001285">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/28/12/640/66cf1903edb746.25949368.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">제주 봄그리고가을 호텔&amp;리조트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">74,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">63%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/28/12/640/66cf1903edb746.25949368.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">제주 봄그리고가을 호텔&amp;리조트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">74,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">63%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3009506">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/11/11/09/640/636e18b235e535.76833874.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">서머셋 제주신화월드</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">132,500</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/11/11/09/640/636e18b235e535.76833874.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">서머셋 제주신화월드</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">132,500</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="2" style="width: 1280px; margin-right: 20px;">
    <div class="items-center px-16 pc:px-0">
    <div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
    <div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3014587">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/07/25/17/640/62decf3e6f7166.32396576.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">베스트웨스턴플러스 경주</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">59,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/07/25/17/640/62decf3e6f7166.32396576.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">베스트웨스턴플러스 경주</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">59,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3012410">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/03/15/09/640/64118bd668d988.31631891.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">스타즈 호텔 울산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">74,900</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">70%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2023/03/15/09/640/64118bd668d988.31631891.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">스타즈 호텔 울산</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">74,900</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">70%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000102831">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/11/30/09/640/638726e4e86694.81461896.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">진주 골든튤립 호텔 남강</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">170,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">15%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/11/30/09/640/638726e4e86694.81461896.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">진주 골든튤립 호텔 남강</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">170,000</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">15%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3012725">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/24/10/640/63566de62ceaa5.56435490.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">통영 스탠포드 호텔앤리조트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]"><span class="typography-body-13-bold pc:typography-subtitle-18-bold text-text-neutral-sub whitespace-nowrap">다른 날짜 확인</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/10/24/10/640/63566de62ceaa5.56435490.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">통영 스탠포드 호텔앤리조트</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]"><span class="typography-body-13-bold pc:typography-subtitle-18-bold text-text-neutral-sub whitespace-nowrap">다른 날짜 확인</span></div></div></div></a></div></div></div></div></div><div class="swiper-slide" data-swiper-slide-index="3" style="width: 1280px; margin-right: 20px;">
    <div class="items-center px-16 pc:px-0">
    <div class="grid grid-cols-2 grid-rows-2 gap-x-12 gap-y-16 pc:flex pc:flex-row pc:justify-between pc:gap-x-20 pc:gap-y-0">
    <div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000102607">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/07/18/14/640/62d56bb8ca3bf4.81887746.png" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">오송 H 호텔 세종시티</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">91,960</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/07/18/14/640/62d56bb8ca3bf4.81887746.png" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">오송 H 호텔 세종시티</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">91,960</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/10054600">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/11/26/06/640/67456cdb714643.71743267.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">제천 리솜 포레스트&amp;레스트리</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">354,400</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/11/26/06/640/67456cdb714643.71743267.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">제천 리솜 포레스트&amp;레스트리</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">354,400</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/3001469">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/30/16/640/66d1f809b29ee2.30056749.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">롯데리조트 부여</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">228,690</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">1%</span></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2024/08/30/16/640/66d1f809b29ee2.30056749.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">롯데리조트 부여</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">228,690</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div><span class="mr-4 typography-subtitle-16-regular text-text-primary-main pc:typography-subtitle-20-regular">1%</span></div></div></div></a></div></div><div><div class="pc:w-[305px]"><a class="text-text-neutral-main mx-auto" href="/hotel/1000112156">
    <div class="text-text-neutral-main pc:hidden">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-10"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/02/10/640/6311e1ae98c3b1.13603366.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="mb-4 overflow-hidden typography-body-14-regular-line-clamp-1">군산 호텔 은파팰리스</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">75,700</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div><div class="text-text-neutral-main w-[305px] hidden pc:block" style="width: 305px;">
    <div class="overflow-hidden aspect-[1/1] pc:aspect-[3/4] rounded-8 pc:rounded-16 relative mb-16"><img alt="Thumbnail" loading="lazy" decoding="async" data-nimg="fill" class="mx-auto size-full bg-fill-neutral-weak1 object-center object-cover" src="https://yaimg.yanolja.com/v5/2022/09/02/10/640/6311e1ae98c3b1.13603366.jpg" style="position: absolute; height: 100%; width: 100%; inset: 0px; color: transparent;">
    <div class="absolute left-4 top-4 pc:left-12 pc:top-12 flex *:mr-2"></div></div><div class="pc:px-4">
    <div class="overflow-hidden typography-subtitle-18-regular-line-clamp-1">군산 호텔 은파팰리스</div><div class="flex flex-row-reverse flex-wrap items-center justify-end h-[2rem] mt-4 overflow-hidden pc:h-[2.4rem]">
    <div class="flex items-center flex-shrink-0"><span class="typography-subtitle-16-bold pc:typography-subtitle-20-bold">75,700</span><span class="typography-body-13-bold pc:typography-subtitle-18-bold">원~</span></div></div></div></div></a></div></div></div></div></div></div></div><div style="top:179px" class="absolute left-0 z-[1] hidden -translate-x-2/4 pc:block"><button aria-disabled="false" class="inline-flex items-center justify-center no-underline select-none appearance-none gap-4 typography-body-14-bold select-none aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed rounded-8 aspect-square min-h-44 pc:min-h-48 rounded-8 shadow-2 bg-static-white outline outline-1 outline-opacity-black-10 aria-disabled:bg-fill-neutral-weak3 hover-never:shadow-3 hover-never:bg-fill-neutral-weak active:shadow-3 active:bg-fill-neutral-weak focus:outline focus:outline-1 focus:outline-opacity-black-10" tabindex="0" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="size-24 pc:size-24"><path fill="currentColor" fill-rule="evenodd" d="M14.603 4.82a1.15 1.15 0 0 1 .045 1.626L9.395 12l5.253 5.554a1.15 1.15 0 0 1-1.67 1.58l-6-6.344a1.15 1.15 0 0 1 0-1.58l6-6.344a1.15 1.15 0 0 1 1.625-.045" clip-rule="evenodd"></path></svg></button></div><div style="top:179px" class="absolute right-0 top-1/2 z-[1] hidden translate-x-2/4 pc:block"><button aria-disabled="false" class="inline-flex items-center justify-center no-underline select-none appearance-none gap-4 typography-body-14-bold select-none aria-disabled:pointer-events-none aria-disabled:cursor-not-allowed rounded-8 aspect-square min-h-44 pc:min-h-48 rounded-8 shadow-2 bg-static-white outline outline-1 outline-opacity-black-10 aria-disabled:bg-fill-neutral-weak3 hover-never:shadow-3 hover-never:bg-fill-neutral-weak active:shadow-3 active:bg-fill-neutral-weak focus:outline focus:outline-1 focus:outline-opacity-black-10" tabindex="0" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="size-24 pc:size-24"><path fill="currentColor" fill-rule="evenodd" d="M8.797 18.813a1.15 1.15 0 0 1 0-1.626L13.983 12 8.797 6.813a1.15 1.15 0 0 1 1.626-1.626l6 6c.449.449.449 1.177 0 1.626l-6 6a1.15 1.15 0 0 1-1.626 0" clip-rule="evenodd"></path></svg></button></div></div></div>